# Generated by Django 2.2.3 on 2019-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('parent_id', models.IntegerField()),
                ('user_email', models.EmailField(max_length=200)),
                ('home_page', models.URLField()),
                ('text', models.TextField(verbose_name='Comment text')),
                ('user_browser', models.TextField(verbose_name='Information about browser')),
                ('user_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
