# Generated by Django 2.2.3 on 2019-07-08 10:32

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[a-zA-Z0-9]'), 'Enter a valid “name” consisting of letters, numbers', 'invalid')]),
        ),
    ]
